# This is a basic workflow to help you get started with Actions

name: Cypress tests

# Controls when the workflow will run
on:
  workflow_dispatch:
  schedule:
    - cron:  '40 * * * *'

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v4
        with:
          build: npm install
